<?php

?>

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
    </head>
    
    <body>
        <form action="ads" method="post">
            <p>id: <input type="text" name="id" /></p>
            <p>title: <input type="text" name="title" /></p>
            <p>author: <input type="text" name="author" /></p>
            <p>tel: <input type="text" name="tel" /></p>
            <p><input type="submit" /></p>
        </form>
    </body>
</html>
